GET http://localhost:8080/api/v1/users/BXQ6bO67tN23ZfgZ4kxrwivjlcJfdRxoIgRjcdLqTwr4pytl5owCa2ChUh4qDCJTK6Aeixvy0cB1AmoyrlSGn4GIm3rMH7VUl6mR
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzkwZTkzLWY1YmMtNGNiNy05MGM4LWRiOThiYzk2MTU2MiIsInVzZXJfaWQiOiJCWFE2Yk82N3ROMjNaZmdaNGt4cndpdmpsY0pmZFJ4b0lnUmpjZExxVHdyNHB5dGw1b3dDYTJDaFVoNHFEQ0pUSzZBZWl4dnkwY0IxQW1veXJsU0duNEdJbTNyTUg3VlVsNm1SIiwiaXNzdWVkX2F0IjoiMjAyMy0wMy0yMFQxMDoxNjo1OC4wNDc0NTcrMDE6MDAiLCJleHBpcmVkX2F0IjoiMjAyMy0wMy0yMFQxMDozMTo1OC4wNDc0NTcrMDE6MDAifQ.bzq81kqwaCsofgstjqknNceGSd5bBspCo8l8s5mSC00